/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GiftKind = IDL.Variant({
  'polaroidMemories' : IDL.Null,
  'loveLetter' : IDL.Null,
  'reasonsILoveYou' : IDL.Null,
});
export const PolaroidMemory = IDL.Record({
  'dateLabel' : IDL.Text,
  'photoKey' : IDL.Text,
  'caption' : IDL.Text,
});
export const GiftContent = IDL.Variant({
  'polaroidMemories' : IDL.Record({ 'memories' : IDL.Vec(PolaroidMemory) }),
  'loveLetter' : IDL.Record({ 'text' : IDL.Text }),
  'reasonsILoveYou' : IDL.Record({ 'reasons' : IDL.Vec(IDL.Text) }),
});

export const idlService = IDL.Service({
  'getGift' : IDL.Func([GiftKind], [GiftContent], ['query']),
  'getGreeting' : IDL.Func(
      [],
      [IDL.Record({ 'name' : IDL.Text, 'couplePhotoKey' : IDL.Text })],
      ['query'],
    ),
  'setBirthdayPhotoKey' : IDL.Func([IDL.Text], [], []),
  'setBoyfriendName' : IDL.Func([IDL.Text], [], []),
  'setCouplePhotoKey' : IDL.Func([IDL.Text], [], []),
  'setLoveLetter' : IDL.Func([IDL.Text], [], []),
  'setLoveMessage' : IDL.Func([IDL.Text], [], []),
  'setPasscode' : IDL.Func([IDL.Text], [], []),
  'setPolaroidMemories' : IDL.Func([IDL.Vec(PolaroidMemory)], [], []),
  'setReasonsILoveYou' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'verifyPasscode' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'birthdayPhotoKey' : IDL.Text,
            'loveMessage' : IDL.Text,
          })
        ),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GiftKind = IDL.Variant({
    'polaroidMemories' : IDL.Null,
    'loveLetter' : IDL.Null,
    'reasonsILoveYou' : IDL.Null,
  });
  const PolaroidMemory = IDL.Record({
    'dateLabel' : IDL.Text,
    'photoKey' : IDL.Text,
    'caption' : IDL.Text,
  });
  const GiftContent = IDL.Variant({
    'polaroidMemories' : IDL.Record({ 'memories' : IDL.Vec(PolaroidMemory) }),
    'loveLetter' : IDL.Record({ 'text' : IDL.Text }),
    'reasonsILoveYou' : IDL.Record({ 'reasons' : IDL.Vec(IDL.Text) }),
  });
  
  return IDL.Service({
    'getGift' : IDL.Func([GiftKind], [GiftContent], ['query']),
    'getGreeting' : IDL.Func(
        [],
        [IDL.Record({ 'name' : IDL.Text, 'couplePhotoKey' : IDL.Text })],
        ['query'],
      ),
    'setBirthdayPhotoKey' : IDL.Func([IDL.Text], [], []),
    'setBoyfriendName' : IDL.Func([IDL.Text], [], []),
    'setCouplePhotoKey' : IDL.Func([IDL.Text], [], []),
    'setLoveLetter' : IDL.Func([IDL.Text], [], []),
    'setLoveMessage' : IDL.Func([IDL.Text], [], []),
    'setPasscode' : IDL.Func([IDL.Text], [], []),
    'setPolaroidMemories' : IDL.Func([IDL.Vec(PolaroidMemory)], [], []),
    'setReasonsILoveYou' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'verifyPasscode' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'birthdayPhotoKey' : IDL.Text,
              'loveMessage' : IDL.Text,
            })
          ),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };