/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type GiftContent = {
    'polaroidMemories' : { 'memories' : Array<PolaroidMemory> }
  } |
  { 'loveLetter' : { 'text' : string } } |
  { 'reasonsILoveYou' : { 'reasons' : Array<string> } };
export type GiftKind = { 'polaroidMemories' : null } |
  { 'loveLetter' : null } |
  { 'reasonsILoveYou' : null };
export interface PolaroidMemory {
  'dateLabel' : string,
  'photoKey' : string,
  'caption' : string,
}
export interface _SERVICE {
  'getGift' : ActorMethod<[GiftKind], GiftContent>,
  'getGreeting' : ActorMethod<
    [],
    { 'name' : string, 'couplePhotoKey' : string }
  >,
  'setBirthdayPhotoKey' : ActorMethod<[string], undefined>,
  'setBoyfriendName' : ActorMethod<[string], undefined>,
  'setCouplePhotoKey' : ActorMethod<[string], undefined>,
  'setLoveLetter' : ActorMethod<[string], undefined>,
  'setLoveMessage' : ActorMethod<[string], undefined>,
  'setPasscode' : ActorMethod<[string], undefined>,
  'setPolaroidMemories' : ActorMethod<[Array<PolaroidMemory>], undefined>,
  'setReasonsILoveYou' : ActorMethod<[Array<string>], undefined>,
  'verifyPasscode' : ActorMethod<
    [string],
    [] | [{ 'birthdayPhotoKey' : string, 'loveMessage' : string }]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];