/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type GiftContent = {
    __kind__: "polaroidMemories";
    polaroidMemories: {
        memories: Array<PolaroidMemory>;
    };
} | {
    __kind__: "loveLetter";
    loveLetter: {
        text: string;
    };
} | {
    __kind__: "reasonsILoveYou";
    reasonsILoveYou: {
        reasons: Array<string>;
    };
};
export interface PolaroidMemory {
    dateLabel: string;
    photoKey: string;
    caption: string;
}
export enum GiftKind {
    polaroidMemories = "polaroidMemories",
    loveLetter = "loveLetter",
    reasonsILoveYou = "reasonsILoveYou"
}
export interface backendInterface {
    getGift(kind: GiftKind): Promise<GiftContent>;
    getGreeting(): Promise<{
        name: string;
        couplePhotoKey: string;
    }>;
    setBirthdayPhotoKey(key: string): Promise<void>;
    setBoyfriendName(name: string): Promise<void>;
    setCouplePhotoKey(key: string): Promise<void>;
    setLoveLetter(text: string): Promise<void>;
    setLoveMessage(message: string): Promise<void>;
    setPasscode(code: string): Promise<void>;
    setPolaroidMemories(memories: Array<PolaroidMemory>): Promise<void>;
    setReasonsILoveYou(reasons: Array<string>): Promise<void>;
    verifyPasscode(attempt: string): Promise<{
        birthdayPhotoKey: string;
        loveMessage: string;
    } | null>;
}
import type { GiftContent as _GiftContent, GiftKind as _GiftKind, PolaroidMemory as _PolaroidMemory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getGift(arg0: GiftKind): Promise<GiftContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getGift(to_candid_GiftKind_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GiftContent_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGift(to_candid_GiftKind_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GiftContent_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGreeting(): Promise<{
        name: string;
        couplePhotoKey: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGreeting();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGreeting();
            return result;
        }
    }
    async setBirthdayPhotoKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBirthdayPhotoKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBirthdayPhotoKey(arg0);
            return result;
        }
    }
    async setBoyfriendName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBoyfriendName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBoyfriendName(arg0);
            return result;
        }
    }
    async setCouplePhotoKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCouplePhotoKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCouplePhotoKey(arg0);
            return result;
        }
    }
    async setLoveLetter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLoveLetter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLoveLetter(arg0);
            return result;
        }
    }
    async setLoveMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLoveMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLoveMessage(arg0);
            return result;
        }
    }
    async setPasscode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPasscode(arg0);
            return result;
        }
    }
    async setPolaroidMemories(arg0: Array<PolaroidMemory>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPolaroidMemories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPolaroidMemories(arg0);
            return result;
        }
    }
    async setReasonsILoveYou(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReasonsILoveYou(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReasonsILoveYou(arg0);
            return result;
        }
    }
    async verifyPasscode(arg0: string): Promise<{
        birthdayPhotoKey: string;
        loveMessage: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPasscode(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPasscode(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_GiftContent_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftContent): GiftContent {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        birthdayPhotoKey: string;
        loveMessage: string;
    }]): {
    birthdayPhotoKey: string;
    loveMessage: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    polaroidMemories: {
        memories: Array<_PolaroidMemory>;
    };
} | {
    loveLetter: {
        text: string;
    };
} | {
    reasonsILoveYou: {
        reasons: Array<string>;
    };
}): {
    __kind__: "polaroidMemories";
    polaroidMemories: {
        memories: Array<PolaroidMemory>;
    };
} | {
    __kind__: "loveLetter";
    loveLetter: {
        text: string;
    };
} | {
    __kind__: "reasonsILoveYou";
    reasonsILoveYou: {
        reasons: Array<string>;
    };
} {
    return "polaroidMemories" in value ? {
        __kind__: "polaroidMemories",
        polaroidMemories: value.polaroidMemories
    } : "loveLetter" in value ? {
        __kind__: "loveLetter",
        loveLetter: value.loveLetter
    } : "reasonsILoveYou" in value ? {
        __kind__: "reasonsILoveYou",
        reasonsILoveYou: value.reasonsILoveYou
    } : value;
}
function to_candid_GiftKind_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftKind): _GiftKind {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftKind): {
    polaroidMemories: null;
} | {
    loveLetter: null;
} | {
    reasonsILoveYou: null;
} {
    return value == GiftKind.polaroidMemories ? {
        polaroidMemories: null
    } : value == GiftKind.loveLetter ? {
        loveLetter: null
    } : value == GiftKind.reasonsILoveYou ? {
        reasonsILoveYou: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
